"""
PDF Report Generator Tool
Creates downloadable PDF reports from analysis results
"""

import os
from datetime import datetime
from fpdf import FPDF


class LeukemiaReportPDF(FPDF):
    """Custom PDF class for medical reports"""
    
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
    
    def header(self):
        # Logo/Title
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(220, 53, 69)  # Red
        self.cell(0, 10, 'LeukemiaScope', align='C', new_x='LMARGIN', new_y='NEXT')
        
        self.set_font('Helvetica', '', 12)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, 'AI Blood Cell Analysis Report', align='C', new_x='LMARGIN', new_y='NEXT')
        
        self.ln(5)
        # Line
        self.set_draw_color(220, 53, 69)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(10)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by LeukemiaScope - MedGemma Impact Challenge 2026', align='C')
    
    def add_section_title(self, title: str):
        """Add a section title"""
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(33, 37, 41)
        self.cell(0, 10, title, new_x='LMARGIN', new_y='NEXT')
        self.ln(2)
    
    def add_field(self, label: str, value: str):
        """Add a label-value pair"""
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(100, 100, 100)
        self.cell(50, 8, label + ":")
        
        self.set_font('Helvetica', '', 10)
        self.set_text_color(33, 37, 41)
        self.cell(0, 8, str(value), new_x='LMARGIN', new_y='NEXT')
    
    def add_result_box(self, classification: str, confidence: float):
        """Add the classification result box"""
        # Background color based on result
        if classification == "Normal":
            bg_color = (34, 197, 94)  # Green
        elif classification == "Leukemia":
            bg_color = (239, 68, 68)  # Red
        else:
            bg_color = (234, 179, 8)  # Yellow
        
        # Draw box
        self.set_fill_color(*bg_color)
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 16)
        
        y_start = self.get_y()
        self.rect(10, y_start, 190, 25, style='F')
        self.set_xy(10, y_start + 5)
        self.cell(190, 8, f"Classification: {classification.upper()}", align='C')
        self.set_xy(10, y_start + 15)
        self.set_font('Helvetica', '', 12)
        self.cell(190, 8, f"Confidence: {confidence:.1%}", align='C')
        
        self.set_y(y_start + 30)
        self.set_text_color(33, 37, 41)
    
    @staticmethod
    def _sanitize_text(text: str) -> str:
        """Remove characters that Helvetica cannot render"""
        return text.encode('latin-1', errors='replace').decode('latin-1')
    
    def add_paragraph(self, text: str):
        """Add a paragraph of text"""
        self.set_font('Helvetica', '', 10)
        self.set_text_color(33, 37, 41)
        clean = self._sanitize_text(text[:1000])  # Limit length
        self.multi_cell(0, 6, clean)
        self.ln(3)
    
    def add_bullet_list(self, items: list):
        """Add a bulleted list"""
        self.set_font('Helvetica', '', 10)
        left = self.l_margin
        for item in items:
            clean = self._sanitize_text(item.lstrip('0123456789. ')[:200])
            self.set_x(left)
            self.cell(8, 6, '-')
            self.multi_cell(0, 6, clean)


def generate_pdf_report(
    patient_name: str,
    patient_dob: str,
    patient_id: str,
    classification: str,
    confidence: float,
    clinical_advice: str = None,
    next_steps: list = None,
    output_path: str = None
) -> str:
    """
    Generate a PDF report
    
    Args:
        patient_name: Patient's full name
        patient_dob: Date of birth
        patient_id: Patient identifier
        classification: "Normal", "Leukemia", or "Uncertain"
        confidence: Model confidence (0-1)
        clinical_advice: Clinical recommendations
        next_steps: List of recommended actions
        output_path: Where to save PDF (optional)
        
    Returns:
        Path to generated PDF
    """
    pdf = LeukemiaReportPDF()
    pdf.add_page()
    
    # Patient Information Section
    pdf.add_section_title("Patient Information")
    pdf.add_field("Name", patient_name or "Not provided")
    pdf.add_field("Date of Birth", patient_dob or "Not provided")
    pdf.add_field("Patient ID", patient_id or "Anonymous")
    pdf.add_field("Report Date", datetime.now().strftime("%Y-%m-%d %H:%M"))
    pdf.ln(5)
    
    # Analysis Results Section
    pdf.add_section_title("Analysis Results")
    pdf.add_result_box(classification, confidence)
    pdf.ln(5)
    
    # Model Information
    pdf.add_field("Analysis Method", "MedGemma 1.5 4B (Fine-tuned LoRA)")
    pdf.add_field("Model ID", "chaudhrysuleman/medgemma-1.5-4b-it-leukemia-lora")
    pdf.add_field("Model Accuracy", "78.15%")
    pdf.add_field("Leukemia Recall", "83.10%")
    pdf.ln(5)
    
    # Clinical Recommendations (if leukemia detected)
    if classification == "Leukemia" and clinical_advice:
        pdf.add_section_title("Clinical Recommendations")
        try:
            pdf.add_paragraph(clinical_advice[:500])
        except Exception:
            pdf.add_paragraph("Clinical recommendations generated. See HTML report for full details.")
        pdf.ln(3)
    
    # Next Steps
    if next_steps:
        pdf.add_section_title("Recommended Next Steps")
        pdf.add_bullet_list([step.lstrip("0123456789. ") for step in next_steps])
        pdf.ln(5)
    
    # Disclaimer Section
    pdf.add_section_title("Important Disclaimer")
    disclaimer = """This report is generated by an AI screening tool for RESEARCH AND EDUCATIONAL PURPOSES ONLY.

This is NOT a medical diagnosis. Results must be confirmed by qualified healthcare professionals. Do not make treatment decisions based solely on this report. Always consult a hematologist or oncologist for definitive diagnosis."""
    
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 5, disclaimer)
    
    # Generate output path
    if output_path is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_name = (patient_name or "anonymous").replace(" ", "_")[:20]
        output_path = f"/tmp/leukemiascope_report_{safe_name}_{timestamp}.pdf"
    
    # Save PDF
    pdf.output(output_path)
    
    return output_path
